### ISSUE TITLE
Arduino Nano 33 BLE Sense and Qwiic OpenLog Issue

### ISSUE THREAD

**Issue by jsabby** [sparkfun/SparkFun_Qwiic_OpenLog_Arduino_Library#14]
I posted earlier in the Sparkfun Forum about an issue concerning error messages I received when trying to compile any example program for the Qwiic OpenLog using the Arduino Nano 33 BLE Sense. It seems to be at some root level inside both the code for Arduino and Openlog fighting over uint8_t and unsigned char. If someone at SparkFun can get a hold of a Nano 33 BLE Sense, would you please put it on a SparkFun Qwiic shield for Nano and connect the Qwiic OpenLog to it and see if you can reproduce this error. I have about 6 or 7 Qwiic sensors the I am using with this Nano and have successfully compiled and ran the example code for all of them. The Qwiic OpenLog is the only is the only piece of hardware giving me a problem.
Thank you

**Comment by jsabby** [comment]
Has anyone at Sparkfun looked into this. I was told in the spark fun forum to post here, but I have not heard back for any Sparkfun engineers. Thank you,

**Comment by nseidle** [comment]
Fixed. Nano 33 BLE has a not-so-great String operator definition.

**Comment by jsabby** [comment]
Thank you very much! I really do appreciate it. I have downloaded the new library and everything is working great.

**Comment by nseidle** [comment]
Awesome! Happy to help.
